name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run production

      - name: Generate Key
        run: php artisan key:generate

      - name: Code climate setup
        run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter

      - name: Code climate run before-build
        run: ./cc-test-reporter before-build

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test --coverage-clover clover.xml --stop-on-failure

      - name: Code climate run after-build
        run: ./cc-test-reporter after-build -t clover --exit-code $?
